# Generated by Django 5.2.6 on 2025-09-08 00:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('periodicity', models.CharField(choices=[('MENSUAL', 'MENSUAL'), ('BIMESTRAL', 'BIMESTRAL'), ('TRIMESTRAL', 'TRIMESTRAL'), ('SEMESTRAL', 'SEMESTRAL'), ('ANUAL', 'ANUAL')], db_index=True, max_length=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='plans_plan_name_4abf9e_idx'), models.Index(fields=['periodicity'], name='plans_plan_periodi_13b273_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='plans.plan')),
            ],
            options={
                'ordering': ['plan_id', 'order'],
                'indexes': [models.Index(fields=['plan', 'name'], name='idx_plan_task_plan_name')],
                'constraints': [models.UniqueConstraint(fields=('plan', 'name'), name='uniq_task_name_per_plan')],
            },
        ),
    ]
