# Generated by Django 5.2.6 on 2025-09-07 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_legal', models.CharField(db_index=True, max_length=200)),
                ('identificacion', models.CharField(max_length=30, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'indexes': [models.Index(fields=['nombre_legal'], name='customers_c_nombre__0a2a34_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='customers.cliente')),
            ],
            options={
                'verbose_name': 'Contacto de cliente',
                'verbose_name_plural': 'Contactos de cliente',
                'indexes': [models.Index(fields=['cliente', 'es_principal'], name='customers_c_cliente_6f133d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('cliente',), name='uniq_principal_por_cliente')],
            },
        ),
    ]
