# Generated by Django 5.2.6 on 2025-09-07 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactocliente',
            name='cliente',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(db_index=True, max_length=200)),
                ('identification', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'indexes': [models.Index(fields=['legal_name'], name='customers_c_legal_n_161986_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Contact',
                'verbose_name_plural': 'Customer Contacts',
            },
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='ContactoCliente',
        ),
        migrations.AddIndex(
            model_name='customercontact',
            index=models.Index(fields=['customer', 'is_primary'], name='customers_c_custome_19e952_idx'),
        ),
        migrations.AddConstraint(
            model_name='customercontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('customer',), name='uniq_primary_contact_per_customer'),
        ),
    ]
