# Generated by Django 5.2.6 on 2025-09-08 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_remove_contactocliente_cliente_customer_and_more'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVA', 'ACTIVA'), ('SUSPENDIDA', 'SUSPENDIDA'), ('CANCELADA', 'CANCELADA')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='customers.customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='plans.plan')),
            ],
            options={
                'db_table': 'subscriptions_plan_subscription',
                'ordering': ['-start_date', 'id'],
                'indexes': [models.Index(fields=['customer', 'plan', 'start_date'], name='idx_subs_c_p_s'), models.Index(fields=['status'], name='idx_subs_status')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'plan', 'start_date'), name='uniq_customer_plan_startdate')],
            },
        ),
    ]
